
IMAGE_HIEGHT = 450
IMAGE_WIDTH = 400

FRAME_SCALE = 0.85
FRAME_WIDTH = int(640 * FRAME_SCALE)
FRAME_HEIGHT = int(480 * FRAME_SCALE)
FRAME_SMALL_WIDTH = 260
FRAME_SMALL_HEIGHT = 250

BACKGROUND1 = "skyblue"
BACKGROUND3 = "grey"
BACKGROUND2 = "lightgrey"
